config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get '/about', to: 'pages#about'
  resources :courses, only: %i[index show]
  resources :students, except: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  delete '/logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, presence: true, length: { minimum: 5, maximum: 10 }
  validates :name, presence: true, length: { minimum: 10, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 50 }
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  before_action :require_user
  def current_user
    current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:notice] = 'You must be logged to perform this action'
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_user, only:[:new,:create]
  def new; end

  def create
    student = Student.find_by(email: params[:logins][:email])
    if student && student.authenticate(params[:logins][:password])
      session[:student_id] = student.id
      flash[:success] = 'You have succcessfully logged in'
      redirect_to student
    else
      flash[:notice] = 'Something wrong with your login information login'
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = 'you have successfully logout'
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about; end
  end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    course = Course.find(params[:course_id])
    if !current_user.courses.include?(course)
      StudentCourse.create(course: course, student: current_user)
      flash[:success]="You have successflly enrollement"
      redirect_to current_user
    else
      flash[:notice] = 'wrong enrollment'
      redirect_to current_user
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: %i[new create]
  before_action :set_student, only: %i[show edit update]
  before_action :require_same_student, only: %i[edit update]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = 'Success you have signed up '
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @student.update(student_params)
      flash[:success] = 'You have successful edited data'
      redirect_to student_path(@student)
    else
      render 'edit'
    end
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def require_same_student
    if current_user != @student
      flash[:success] = 'You can only edit your own profil'
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<div class="row">
    <div class="col s12">
        <h2 class="center-align">Courses List</h2>
    </div>
</div>

<div class="row">
   
    
      <% @courses.all.each  do  |course| %>
        <div class="col s12 m6">
          <div class="card orange darken-4">
              <div class="card-content white-text">
                <span class="card-title"><%=course.short_name %> <%=course.name %></span>
                <p><%=course.description %></p>
              </div>
              <div class="card-action">
                <% if logged_in? && !current_user.courses.include?(course) %>
                  <%= link_to 'Enroll', course_enroll_path(course_id: course.id),method: :post %>
                <% end %>
                <%= link_to 'details', course_path(course) %>
              </div>
            </div>
          </div>
          
      <% end %>
    
  
    </div>

app/views/courses/show.html.erb
<div class="row">
    <div class="col s12">
        <h2 class="center-align">Course details</h2>
    </div>
</div>

<div class="row">
        <div class="col s12 m12">
          <div class="card grey darken-4">
              <div class="card-content white-text">
                <span class="card-title"><%=@course.short_name %> <%=@course.name %></span>
                <p><%=@course.description %></p>
              </div>
              <div class="card-action">
                <%= link_to 'Back', root_path ,class: "btn"%>
              </div>
            </div>
          </div>   
  
    </div>

app/views/layouts/_footer.html.erb
 <footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">My University</h5>
                <p class="grey-text text-lighten-4">Self teaching is the future .</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Contact</h5>
                <ul>
                    <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
                    <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © 2020 M University
            <a class="grey-text text-lighten-4 right" href="#!">More</a>
        </div>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
 <header>
     <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
          <% if logged_in? %>
          <li><%= link_to 'logout', logout_path ,method: :delete %></li>
        <% else %>
          <li><%= link_to 'login', login_path %></li>
           <li class="divider"></li>
        <li><%= link_to 'Sign_up', new_student_path %></li>
        <% end %>
       
    </ul>
    <ul id="dropdown2" class="dropdown-content">
        <% if logged_in? %>
          <li><%= link_to 'logout', logout_path %></li>
        <% else %>
          <%= link_to 'login', login_path %>
        <% end %>
        <li class="divider"></li>
        <li><a href="#!">three</a></li>
    </ul>
    <nav>
        <div class="container">
            <div class="nav-wrapper">
                <%= link_to 'myUniversity',root_path,class:'brand-logo right' %>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    <li><%= link_to 'Courses', root_path %></li>
                    <% if logged_in? %>
                      <li><%= link_to 'Students', students_path %></li>
                    <% end %>
                    
                    <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
                </ul>
            </div>
        </div>
    </nav>

    <ul class="sidenav" id="mobile-demo">
        <li><a href="#">Courses</a></li>
        <li><a href="#">Enrollement</a></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
    <div class="container">
        <div class="row center sign-up-form">
            <div class="col s12 m12 l12">
                <% flash.each do |key,msg| %>
                <div class="card-panel blue lighten-2 left-align" id="fade-out-target">
                    <span class="white-text">
                        
                            <ul>
                                <li><%= msg %></li>
                            </ul>
                      
                    </span>
                </div>
                <% end %>
            </div>
        </div>
    </div>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyUniversity</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
    <div class="row center sign-up-form">
        <div class="col s12 m12 l12">
            <div class="card-panel">
                <h3 class="center-align">Login in</h3>
                <div class="row">
                        <%= form_for(:logins,html:{class: "col s12"}) do |f| %>


                    <div class="row">
                        <div class="input-field col s12">
                             <%= f.email_field :email ,placeholder:"enter your email"%>
                             <%= f.label :email ,class:"active"%>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                             <%= f.password_field :password ,placeholder:"enter your password"%>
                             <%= f.label :password ,class:"active"%>
                        </div>
                    </div>

     

                    <%= f.button "log in",class:"waves-effect waves-light blue btn" %>
 
                <% end %>
                </div>
            
            </div>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<h1>About Page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="container">
    <div class="row center sign-up-form">
        <div class="col s12 m12 l12">
            <div class="card-panel red lighten-2 left-align">
                <span class="white-text">
                    <%=pluralize(obj.errors.count,"error") %>
                    <ul>
                    <% obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                    </ul>
                </span>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors',obj:@student %>
<div class="container">
    <div class="row center sign-up-form">
        <div class="col s12 m12 l12">
            <div class="card-panel">
                <h3 class="center-align"><%= @student.new_record? ? "Sign up" : "Edit student" %></h3>
                <div class="row">
                        <%= form_for(@student,html:{class: "col s12"}) do |f| %>
                    <div class="row">
                        <div class="input-field col s12">
                             <%= f.text_field :name ,placeholder:"Enter your name"%>
                             <%= f.label :name ,class:"active"%>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                             <%= f.email_field :email ,placeholder:"enter your email"%>
                             <%= f.label :email ,class:"active"%>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                             <%= f.password_field :password ,placeholder:"choose your password"%>
                             <%= f.label :password ,class:"active"%>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                             <%= f.password_field :password_confirmation ,placeholder:"confirm your password"%>
                             <%= f.label :password_confirmation,class:"active" %>
                        </div>
                    </div>

                    <%= f.submit @student.new_record? ? :"submit":"Edit",class:"waves-effect waves-light blue btn" %>
 
                <% end %>
                </div>
            
            </div>
        </div>
    </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
    <div class="col s12">
        <h2 class="center-align">Student List</h2>
    </div>
</div>

<div class="row">
    <% @students.each do |student| %>
    <div class="col s12 m4">
      <div class="card orange darken-4">
        <div class="card-content white-text">
          <span class="card-title">Name:<%= student.name %></span>
          <p>Email: <%= student.email %></p>
        </div>
        <div class="card-action">
          <a href="#">Enroll</a>
          <%= link_to 'Info', student_path(student.id) %>
        </div>
      </div>
    </div>
    <% end %>
 

</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row">
    <div class="col s12">
        <h2 class="center-align">Show student</h2>
    </div>
</div>
<div class="container">
    <div class="col s12 m12">
      <div class="card orange darken-4">
        <div class="card-content white-text">
          <span class="card-title">Name:<%= @student.name %></span>
          <p>Email: <%= @student.email %></p>
          <p>
            <span>Course enrollement:</span>
            <ul>
              <% @student.courses.each do |course| %>
                  <li><%= course.name %></li>
              <% end %>
            </ul>
          </p>
        </div>
        <div class="card-action">
          <%= link_to edit_student_path(@student) ,class:"waves-effect waves-light  grey darken-2 btn"  do %>
                Edit profil <i class="material-icons right">create</i>
          <% end %>
        </div>
      </div>
    </div>
</div>

 